project:
  type: website
  resources: 
    - libs/
    - images/
    - CNAME
  
website:
  title: "Bayesically Speaking"
  description: "The place where statistics, coffee and bayes theorem come toghether"
  favicon: "images/logo.png"
  site-url: https://bayesically-speaking.com/
  navbar:
    background: primary
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - icon: github
        href: https://github.com/matcasti
      - icon: twitter
        href: https://twitter.com/matias_science
      - icon: rss
        href: blog.xml
        
format:
  html:
    fig-format: svg
    theme: libs/styles.scss



