---
title: "[Portfolio]{.d-none}"
title-block-banner: false
bibliography: libs/portfolio.bib
csl: libs/portfolio.csl
toc: true
---

<!--- Replacement of title-block: START ---->

[Portfolio]{.display-2 .position-absolute .text-light style="z-index:3; top:45vh;"}

<div class="vh-100 w-100 top-0 position-absolute" style="background-color: rgb(0,0,0,0.3); z-index:2;"></div>

:::{.column-screen .position-absolute .w-100 .top-0 style="z-index:1;"}
```{=html}
<video autoplay loop muted poster="images/portfolio_title_block.jpg" style="height: 100vh; width: 100%; object-fit: cover;">
<source src="images/portfolio_title_block.mp4" type="video/mp4">
</video>
```
:::

<style>
.zindex-over-content{
  display: none;
}
</style>

<div class="vh-100"></div>
<!--- Replacement of title-block: END ---->

# Research

Throughout my research career, I have focused primarily on investigating the impact of exercise and physical activity on cardiac autonomic modulation in athletes and older individuals. Additionally, I have explored the influence of various variables on this relationship, aiming to gain a comprehensive understanding of this complex interplay. Moreover, I have actively engaged in collaborative efforts outside my core research domain, leveraging my expertise in applied statistics and Bayesian data analysis to contribute valuable insights.

In the following section, I present a summary of the research endeavors I have undertaken since 2021, which have shaped my expertise and contributed to the advancement of knowledge in my field.

## Journal articles

:::{.grid}

:::{.g-col-12}
### 2021
:::

:::{.g-col-12 .g-col-sm-6}
Association between body mass index and regulation of the cardiovascular system in medical students. *Archivos de Medicina (Manizales)*.

[Caren Alvarado-Aravena, [Matías Castillo-Aguilar]{.text-body}, Hector Felipe Retamal Matus, Claudia Estrada Goic & Cristian Núñez Espinosa.]{.small .text-black-50}

<a class="btn btn-outline-primary" href="https://www.medigraphic.com/pdfs/manizales/amm-2021/amm212h.pdf">Full-text {{< fa link >}}</a>
:::

:::{.g-col-12 .g-col-sm-6}
Cardiac autonomic modulation in response to muscle fatigue and sex differences during consecutive competition periods in young swimmers: A longitudinal study. *Frontiers in Physiology*.

[[Matías Castillo-Aguilar]{.text-body}, Pablo Valdés-Badilla, Tomás Herrera-Valenzuela, Eduardo Guzmán-Muñoz, Pedro Delgado-Floody, David Cristóbal Andrade, Michele Moraes, Rosa Arantes & Cristian Núñez-Espinosa]{.small .text-black-50}

<a class="btn btn-outline-primary" href="https://www.frontiersin.org/articles/10.3389/fphys.2021.769085/full">Full-text {{< fa link >}}</a>
:::

:::{.g-col-12}
### 2022
:::

:::{.g-col-12 .g-col-sm-6}
[Patricio Barría Aburto, Vanessa Ruiz Barría, [Matías Castillo-Aguilar]{.text-body}, Rolando Aguilar Cárdenas, Asterio Andrade Gallardo & Cristian Núñez-Espinosa]{.small .text-black-50}

Functional characterization of patients with cerebral palsy living 
in the Magallanes region and the Chilean Antarctic. *Andes pediatrica*.

<a class="btn btn-outline-primary" href="https://www.scielo.cl/pdf/andesped/v93n3/en_2452-6053-andesped-andespediatr-v93i3-3636.pdf">Full-text {{< fa link >}}</a>
:::


:::{.g-col-12 .g-col-sm-6}
[[Matías Castillo-Aguilar]{.text-body}, Hector Felipe Retamal Matus, Roberto Santa Cruz, Ygor Tinoco Martins, Oscar Niño Méndez & Cristian Núñez-Espinosa]{.small .text-black-50}

Relationship of cardiorespiratory control and vascular compliance in competitive young athletes. *Revista Andaluza de Medicina del Deporte*.

<a class="btn btn-outline-primary" href="https://dialnet.unirioja.es/servlet/articulo?codigo=8941514">Full-text {{< fa link >}}</a>
:::

:::{.g-col-12 .g-col-sm-6}
[[Matías Castillo-Aguilar]{.text-body}, Vania Castillo-Aguilar, Caren Alvarado-Aravena, Rodrigo Yáñez-Yáñez, Zoila Esperanza Leiton-Espinoza & Igor Cigarroa]{.small .text-black-50}

Clinical characteristics, comorbidity, and laboratory variables associated with hospitalization and mortality in older people with Covid-19: A systematic review. *Revista Cientı́fica Salud Uninorte*.

<a class="btn btn-outline-primary" href="https://dx.doi.org/10.14482/sun.38.3.616.24">Full-text {{< fa link >}}</a>
:::

:::{.g-col-12 .g-col-sm-6}
[Caren Alvarado-Aravena, Karem Arriaza, [Matías Castillo-Aguilar]{.text-body}, Karen Flores, Alexies Dagnino-Subiabre, Claudia Estrada-Goic & Cristian Núñez-Espinosa]{.small .text-black-50}

Effect of confinement on anxiety symptoms and sleep quality during the COVID-19 pandemic. *Behavioral Sciences*.

<a class="btn btn-outline-primary" href="https://doi.org/10.3390/bs12100398">Full-text {{< fa link >}}</a>
:::

:::{.g-col-12}
### 2023
:::

:::{.g-col-12 .g-col-sm-6}
[Caren Alvarado-Aravena, [Matías Castillo-Aguilar]{.text-body}, Valeska Villegas, Claudia Estrada Goic, Katherine Harris, Patricio Barría, Michele Moraes, Thiago Mendes, Rosa Arantes, Pablo Valdés-Badilla & Cristian Núñez-Espinosa]{.small .text-black-50}

Physical activity, seasonal sensitivity and psychological well-being of people of different age groups living in extreme environments. *International Journal of Environmental Research and Public Health*.

<a class="btn btn-outline-primary" href="https://doi.org/10.3390/ijerph20031719">Full-text {{< fa link >}}</a>
:::

:::{.g-col-12 .g-col-sm-6}
[[Matías Castillo-Aguilar]{.text-body}, Matías Mabe Castro, Diego Mabe Castro, Pablo Valdés-Badilla, Tomás Herrera-Valenzuela, Eduardo Guzmán-Muñoz, Morin Lang, Oscar Niño Méndez & Cristian Núñez-Espinosa]{.small .text-black-50}

Validity and reliability of short-term heart rate variability parameters in older people in response to physical exercise. *International Journal of Environmental Research and Public Health*.

<a class="btn btn-outline-primary" href="https://doi.org/10.3390/ijerph20054456">Full-text {{< fa link >}}</a>
:::

:::{.g-col-12 .g-col-sm-6}
[[Matías Castillo-Aguilar]{.text-body}, Diego Mabe Castro, Matías Mabe Castro, Valeska Oyarzo, Katherine Harris, Pablo Valdés-Badilla, Pedro Delgado Floody, Javiera Gonzalez & Cristian Núñez-Espinosa]{.small .text-black-50}

Cardiac autonomic regulation in response to functional power threshold testing in elite cyclists. *Revista Andaluza de Medicina del Deporte*

<a class="btn btn-outline-primary" href="https://ws208.juntadeandalucia.es/ojs/index.php/ramd/article/view/1109">Full-text {{< fa link >}}</a>
:::

:::

<!--- #### --->

## Conference papers

:::{.grid}

:::{.g-col-12}
### 2021
:::

:::{.g-col-12 .g-col-sm-6}
[Katherine Harris King, [Matías Castillo-Aguilar]{.text-body}, Patricio Barría, Rolando Aguilar, Hector Felipe Retamal & Cristian Núñez-Espinosa]{.small .text-black-50}

Propiedades cinemáticas de rodilla en respuesta a la posición de cuclillas: Implicancias para la rehabilitación. *Congreso IBERDISCAP*.

<a class="btn btn-outline-primary" href="https://www.researchgate.net/publication/356641287_Propiedades_cinematicas_de_rodilla_en_respuesta_a_la_posicion_de_cuclillas_implicancias_para_la_rehabilitacion">Full-text {{< fa link >}}</a>
:::

:::

# Software & Web design

As you can imagine, the act of creating this website constitutes a web design project itself, however I've also created websites and software in the context
